# Generated by Django 3.2.16 on 2024-12-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True, help_text='Поставить галочку для публикации')),
                ('path_to_product', models.TextField(help_text='Путь до фотки товара', max_length=128)),
                ('info', models.TextField(verbose_name='информация о товаре')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.categories')),
            ],
            options={
                'verbose_name': 'Вещь(1шт)',
                'verbose_name_plural': 'Товары(много)',
            },
        ),
    ]
